# .pre-commit-config.yaml
repos:
-   repo: https://github.com/h-iqbal/cfn-lint-template.git
    rev: v0.22.3 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
    files: .*\.(json|yml|yaml)$
