repos:
-   repo: https://github.com/h-iqbal/cfn-lint-template.git
    rev: v1.0 # The version of cfn-lint to use
    hooks:
    -   id: cfn-lint
    files: /home/ec2-user/cfn-lint-template/.*\.(json|yml|yaml)$
